In [ ]:
def generate_matrix (n):
	if n <= 0:
		return []
	result = [[0] * n for _ in range(n)]
	left, right = 0 , n - 1
	top, bottom = 0 , n - 1
	num = 1

	while left <= right and top <= bottom:
		for i in range(left, right + 1):
			result[top][i] = num
			num += 1
		top += 1

		for i in range(top , bottom + 1):
			result[i][right] = num
			num += 1
		right -= 1
		
		for i in range(right, left - 1, -1):
			result[bottom][i] = num
			num += 1
		bottom -= 1

		for i in range(bottom, top - 1, -1):
			result[i][left] = num
			num += 1
		left += 1

	return result

generate_matrix(3)

In [ ]:
def comb_sort(items):
    gap = len(items)
    shrink = 1.3
    sorted = False
    while not sorted:
        gap = int(gap // shrink)
        if gap <= 1:
            gap = 1  # 確保 gap 不會變成 0
            sorted = True
        for i in range(len(items) - gap):
            if items[i] > items[i + gap]:
                items[i], items[i + gap] = items[i + gap], items[i]
    return items  # 直接返回排序後的 items

items = [99, 73, 6, 20, 8, 19, 56, 65,  23, 87, 41, 49, 53, 14]
print(comb_sort(items))

In [23]:
def reverseString(params):
    newStr = list(str(params))
    left = 0
    right = len(newStr) - 1
    while left < right:
        newStr[left], newStr[right] = newStr[right], newStr[left]
        left += 1
        right -= 1
    return "".join(newStr)

result = reverseString('lewis.lee')
print(result)

eel.siwel


In [22]:
def binarySearch(nums, target):
	left = 0
	right = len(nums) - 1
	while left <= right:
		middle = (left + right) // 2
		if nums[middle] > target:
			right = middle - 1
		elif nums[middle] < target:
			left = middle + 1
		else:
			return middle
	return -1

result = binarySearch([1,2,3,4,5,8,9,50,99], 99)
result

8

In [15]:
import random

class ListNode:
	def __init__(self, value=0, next=None):
		self.value = value
		self.next = None

class MyLinkedList:
	def __init__(self):
		self.dummyHead = ListNode()
		self.size = 0

	def get(self, index):
		if index < 0 or index >= self.size:
			return -1
		current = self.dummyHead.next
		for _ in range(index):
			current = current.next

		return current.value
	
	def addAtIndex (self, index, value):
		if index < 0 or index > self.size:
			return

		newNode = ListNode(value)
		prev = self.dummyHead
		for _ in range(index):
			prev = prev.next

		newNode.next = prev.next
		prev.next = newNode
		self.size += 1
	
	def addAtTail(self, value):
		self.addAtIndex(self.size, value)

	def deleteAtIndex(self, index):
		if index < 0 or index >= self.size:
			return
		
		prev = self.dummyHead
		for _ in range(index):
			prev = prev.next
		
		prev.next = prev.next.next
		self.size -= 1


myList = MyLinkedList()
for _ in range(10):
    myList.addAtTail(random.randint(1, 100))

print("鍊錶中的值：")
for i in range(10):
    print(f"索引 {i}: {myList.get(i)}")

print('---')
myList.deleteAtIndex(5)
for i in range(10):
    print(f"索引 {i}: {myList.get(i)}")

鍊錶中的值：
索引 0: 98
索引 1: 24
索引 2: 44
索引 3: 55
索引 4: 56
索引 5: 75
索引 6: 81
索引 7: 100
索引 8: 8
索引 9: 55
---
索引 0: 98
索引 1: 24
索引 2: 44
索引 3: 55
索引 4: 56
索引 5: 81
索引 6: 100
索引 7: 8
索引 8: 55
索引 9: -1


In [43]:
def getRangeSum(nums, left, right):
	prefix_sums = [0] * (len(nums) + 1)

	for i in range(1, len(nums) + 1):
		prefix_sums[i] = prefix_sums[i - 1] +  nums[i - 1]

	return prefix_sums[right + 1] - prefix_sums[left]

result = getRangeSum([1, 2, 3, 4, 5], 0, 4)
result

15

In [19]:
from collections import deque

def maxSlidingWindow(nums, k):
	if(len(nums) ==0 or k<= 0):
		return []
	
	deq = deque()
	result = []

	for i in range(len(nums)):
		if deq and deq[0] <= i - k:
			deq.popleft()

		while deq and nums[deq[-1]] <= nums[i]:
			deq.pop()

		deq.append(i)
		
		if i >= k - 1:
			result.append(nums[deq[0]])

	return result

res = maxSlidingWindow([1,3,-1,99,-3,5,3,6,7], 3)
res

[3, 99, 99, 99, 5, 6, 7]

In [6]:
def three_sum(nums: list) -> list:
	result = []
	nums.sort()
	for i in range(len(nums) - 2):
		if nums[i] > 0:
			return result
		left = i + 1
		right = len(nums) - 1
		if i > 0 and nums[i] == nums[i - 1]:
			continue
		if nums[i] > 0:
			break
		while right > left:
			total = nums[left] + nums[right] + nums[i]
			if total < 0:
				left += 1
			elif total > 0:
				right -= 1
			else:
				result.append([nums[left] , nums[right] , nums[i]])
				while nums[left] == nums[left + 1]:
					left += 1
				while nums[right] == nums[right - 1]:
					right -= 1
				left += 1
				right -= 1
	return result

nums = [-1, 0, 1, 2, -1, -4]
res = three_sum(nums)
res

[[-1, 2, -1], [0, 1, -1]]

In [5]:
def insertion_sort(items):
	for i in range(len(items)):
		j = i
		while(j > 0 and (items[j - 1]) > items[j]):
			items[j - 1], items[j] = items[j], items[j - 1]
	return items

items = [6,20,8,19,56,23,87,41,49,53]
print(insertion_sort(items))

[6, 8, 19, 20, 23, 56, 41, 49, 53, 87]


In [44]:
values = [15, 20 ,30]
weights = [1, 2, 4]
n = len(values)

def get_max_values_of_bag(values, weights, bag_weights):
	dp = [[0] * (bag_weights + 1) for _ in range(n)]
	for j in range(weights[0], bag_weights + 1):
		dp[0][j] = values[0]

	for i in range(1, n):
		for j in range(bag_weights + 1):
			if j < weights[i]:
				dp[i][j] = dp[i - 1][j]
			else:
				dp[i][j] = max(dp[i - 1][j], dp[i - 1][j - weights[i]] + values[i])

	print("--- 2D DP Table ---")
	for row in dp:
		print(row)
	print("-------------------")

	return dp[n - 1][bag_weights]

res = get_max_values_of_bag(values, weights, bag_weights = 4)
res

--- 2D DP Table ---
[0, 15, 15, 15, 15]
[0, 15, 20, 35, 35]
[0, 15, 20, 35, 35]
-------------------


35

In [43]:
def canPartition_2D_numeric(nums):
    total_sum = sum(nums)

    if total_sum % 2 != 0:
        return False

    target = total_sum // 2
    # dp[i][j] 表示使用前 i 個數字，能湊出不大於 j 的最大和
    dp = [[0] * (target + 1) for _ in range(len(nums) + 1)] # 為了方便處理 dp[0][j] 和 dp[i][0]，通常會多加一行一列

    # i 從 1 開始代表 nums 的第 0 個數字 (dp[1] 對應 nums[0])
    for i in range(1, len(nums) + 1):
        current_num = nums[i - 1] # 當前考慮的數字

        for j in range(target + 1):
            # 不包含當前數字 nums[i-1]
            dp[i][j] = dp[i - 1][j]

            # 嘗試包含當前數字 nums[i-1]
            if j >= current_num:
                # 如果包含後，能湊出更大的和，就更新
                dp[i][j] = max(dp[i][j], dp[i - 1][j - current_num] + current_num)

    # 打印 dp 陣列，方便觀察
    print("--- 2D DP Table ---")
    for row in dp:
        print(row)
    print("-------------------")

    return dp[len(nums)][target] == target

res_2d = canPartition_2D_numeric([1, 5, 11, 5])
print(f"2D DP Result: {res_2d}")

--- 2D DP Table ---
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 1, 1, 1, 1, 5, 6, 6, 6, 6, 6, 6]
[0, 1, 1, 1, 1, 5, 6, 6, 6, 6, 6, 11]
[0, 1, 1, 1, 1, 5, 6, 6, 6, 6, 10, 11]
-------------------
2D DP Result: True


In [47]:
def canPartition_1D_numeric(nums):
    total_sum = sum(nums)

    if total_sum % 2 != 0:
        return False

    target = total_sum // 2
    dp = [0] * (target + 1)


res_1d = canPartition_1D_numeric([1, 5, 11, 5])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [10]:
def lastStoneWeightII(stones):
	total_sum = sum(stones)
	target = total_sum // 2
	n = len(stones)
	dp = [[0] * (target + 1) for _ in range(n)]

	for j in range(target + 1):
		if j >= stones[0]:
			dp[0][j] = stones[0]
	
	for i in range(1, n):
		for j in range(target + 1):
			if j < stones[i]:
				dp[i][j] = dp[i - 1][j]
			else: 
				dp[i][j] = max(dp[i - 1][j], dp[i - 1][j - stones[i]] + stones[i])

	print("--- 2D DP Table ---")
	for row in dp:
		print(row)
	print("-------------------")

	return total_sum - dp[n - 1][target] - dp[n - 1][target]
	

res = lastStoneWeightII([2,7,4,1,8,1])
res

--- 2D DP Table ---
[0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
[0, 0, 2, 2, 2, 2, 2, 7, 7, 9, 9, 9]
[0, 0, 2, 2, 4, 4, 6, 7, 7, 9, 9, 11]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
-------------------


1

In [32]:
import os
import shutil

def classify_images(source_folder, images_per_folder=20, start_folder_num=1):
    """
    將資料夾中的圖檔分類到新的資料夾中，每個資料夾包含指定數量的圖檔。

    Args:
        source_folder (str): 包含原始圖檔的資料夾路徑。
        images_per_folder (int): 每個分類資料夾中要放置的圖檔數量。
    """

    if not os.path.isdir(source_folder):
        print(f"錯誤：來源資料夾 '{source_folder}' 不存在。")
        return

    # 1. 取得所有圖檔
    image_files = []
    for filename in os.listdir(source_folder):
        # 這裡可以根據實際的圖檔類型進行篩選
        if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp', '.tiff')):
            image_files.append(os.path.join(source_folder, filename))

    if not image_files:
        print(f"在 '{source_folder}' 中找不到任何圖檔。")
        return

    # 2. 排序圖檔 (按檔名排序)
    image_files.sort()

    # 3. 計算資料夾數量
    num_images = len(image_files)
    num_folders = (num_images + images_per_folder - 1) // images_per_folder # 向上取整

    print(f"找到 {num_images} 個圖檔，將分為 {num_folders} 個資料夾。")

    # 4. 建立資料夾並移動圖檔
    for i in range(num_folders):
        # 資料夾名稱格式化為三位數，例如 001, 002, ...
        folder_name = f"{i + start_folder_num:03d}"
        destination_folder = os.path.join(os.path.dirname(source_folder), folder_name) # 將新資料夾建立在與來源資料夾同層級

        os.makedirs(destination_folder, exist_ok=True) # exist_ok=True 避免重複建立錯誤

        start_index = i * images_per_folder
        end_index = min((i + 1) * images_per_folder, num_images)
        files_to_move = image_files[start_index:end_index]

        print(f"正在處理資料夾 '{folder_name}'，包含 {len(files_to_move)} 個圖檔...")
        for file_path in files_to_move:
            try:
                shutil.move(file_path, destination_folder)
                # print(f"  移動 '{os.path.basename(file_path)}' 到 '{folder_name}'")
            except Exception as e:
                print(f"移動檔案 '{os.path.basename(file_path)}' 時發生錯誤：{e}")

    print("圖檔分類完成！")


classify_images('/Users/lewis/Desktop/Project2/stable-diffusion-webui/outputs/txt2img-images/2025-06-16',
                 images_per_folder=12,
                 start_folder_num=20)

找到 39 個圖檔，將分為 4 個資料夾。
正在處理資料夾 '020'，包含 12 個圖檔...
正在處理資料夾 '021'，包含 12 個圖檔...
正在處理資料夾 '022'，包含 12 個圖檔...
正在處理資料夾 '023'，包含 3 個圖檔...
圖檔分類完成！


In [ ]:
import os
import shutil

def flatten_images(target_directory=".", delete_empty_folders=True):
    """
    將指定目錄及其所有子目錄中的圖檔攤平到指定目標目錄。

    Args:
        target_directory (str): 圖檔最終要移動到的目標目錄。預設為當前目錄。
        delete_empty_folders (bool): 是否刪除移動圖檔後變空的子資料夾。預設為 True。
    """

    # 確保目標目錄存在
    os.makedirs(target_directory, exist_ok=True)

    # 儲存所有要處理的圖檔路徑
    image_paths = []
    # 儲存所有處理過的資料夾，以便後續刪除空的
    processed_folders = []

    print(f"正在掃描 '{os.path.abspath(target_directory)}' 及其子目錄中的圖檔...")

    # 遍歷當前目錄及其所有子目錄
    for root, dirs, files in os.walk(target_directory):
        # 排除目標目錄本身，避免移動到自己
        if root == target_directory:
            continue

        processed_folders.append(root) # 記錄這個資料夾，可能需要刪除

        for filename in files:
            # 判斷是否為圖檔 (你可以根據需要增減副檔名)
            if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp', '.tiff', '.webp')):
                source_path = os.path.join(root, filename)
                image_paths.append(source_path)

    if not image_paths:
        print("沒有找到任何圖檔需要攤平。")
        return

    print(f"找到 {len(image_paths)} 個圖檔，準備進行攤平操作...")

    # 移動圖檔
    for original_path in image_paths:
        file_name = os.path.basename(original_path)
        destination_path = os.path.join(target_directory, file_name)

        # 處理檔名衝突：如果目標目錄已經有同名檔案，則重新命名
        counter = 1
        while os.path.exists(destination_path):
            name, ext = os.path.splitext(file_name)
            destination_path = os.path.join(target_directory, f"{name}_{counter}{ext}")
            counter += 1

        try:
            shutil.move(original_path, destination_path)
            # print(f"  已移動 '{os.path.basename(original_path)}' 到 '{target_directory}'")
        except Exception as e:
            print(f"移動檔案 '{os.path.basename(original_path)}' 時發生錯誤：{e}")

    print("所有圖檔已攤平。")

    # 刪除空的子資料夾
    if delete_empty_folders:
        print("正在檢查並刪除空的子資料夾...")
        # 從最深的子資料夾開始刪除，避免父資料夾被過早刪除
        for folder in sorted(processed_folders, key=len, reverse=True):
            try:
                # 再次檢查確保資料夾確實是空的，因為可能被其他檔案佔用
                if not os.listdir(folder):
                    os.rmdir(folder)
                    # print(f"  已刪除空的資料夾: '{folder}'")
            except OSError as e:
                # 如果資料夾不為空或有權限問題，會拋出 OSError
                # print(f"  無法刪除資料夾 '{folder}' (可能不為空或權限問題)：{e}")
                pass # 忽略無法刪除的資料夾

        print("空的子資料夾檢查完成。")


flatten_images('/Users/lewis/Desktop/Project2/stable-diffusion-webui/outputs/txt2img-images')

In [31]:
def bi_search(nums, target):
	left = 0
	right = len(nums) - 1
	while left <= right:
		mid = (left + right) // 2
		if nums[mid] > target:
			right = mid - 1
		elif nums[mid] < target:
			left = mid + 1
		else:
			return mid
	return -1

bi_search([-1, 0, 3, 5, 9, 12, 16, 18 ,20, 90, 109], 18)

7

In [6]:
def find_max_content_children(g, s):
	g.sort()
	s.sort()
	index = len(s) - 1
	max_chidren = 0
	for i in range(len(g) - 1, -1, -1):
		if index >= 0 and s[index] >= g[i]:
			max_chidren += 1
			index -= 1
	return max_chidren

find_max_content_children(g = [1, 2, 4], s = [1, 2, 3])

2

In [53]:
def findTargetSumWays(nums, target):
	count = [0]
	backtrack(0, 0, nums, target, count)
	return count[0]

def backtrack(current_index, current_sum, nums, target, count):
	if current_index == len(nums):
		if current_sum == target:
			count[0] += 1
		return
	
	backtrack(current_index + 1, current_sum + nums[current_index], nums, target, count)
	backtrack(current_index + 1, current_sum - nums[current_index], nums, target, count)

nums = [1, 1, 1, 1, 1]
target = 3
result = findTargetSumWays(nums, target)
print(f"數字 {nums} 達到目標 {target} 的方法總數：{result}") # 輸出: 數字 [1, 1, 1, 1, 1] 達到目標 3 的方法總數：5

print("-" * 30)

nums2 = [1]
target2 = 1
result2 = findTargetSumWays(nums2, target2)
print(f"數字 {nums2} 達到目標 {target2} 的方法總數：{result2}") # 輸出: 數字 [1] 達到目標 1 的方法總數：1

print("-" * 30)

nums3 = [100]
target3 = -200
result3 = findTargetSumWays(nums3, target3)
print(f"數字 {nums3} 達到目標 {target3} 的方法總數：{result3}") # 輸出: 數字 [100] 達到目標 -200 的方法總數：0

數字 [1, 1, 1, 1, 1] 達到目標 3 的方法總數：5
------------------------------
數字 [1] 達到目標 1 的方法總數：1
------------------------------
數字 [100] 達到目標 -200 的方法總數：0


In [45]:
def my_decorator(func):
	def wrapper():
		print("Before calling")
		func()
		print("After calling")
	return wrapper

@my_decorator
def say_hello():
	print("middleware")

say_hello()

Before calling
middleware
After calling


In [46]:
import torch

# 案例 1：基本矩陣轉置
def example1_basic_transpose():
    # 創建一個 2x3 的張量
    A = torch.tensor([[1, 2, 3],
                      [4, 5, 6]], dtype=torch.float)
    # 執行轉置操作，得到 3x2 張量
    A_T = A.transpose(0, 1)
    print("案例 1：基本矩陣轉置")
    print("原始張量 A:\n", A)
    print("轉置後張量 A^T:\n", A_T)

# 案例 2：數據處理中的轉置
def example2_data_processing():
    # 模擬三個學生的兩門課成績（數學、英語）
    scores = torch.tensor([[90, 85],
                           [88, 92],
                           [76, 80]], dtype=torch.float)
    # 轉置以按科目組織數據
    scores_T = scores.transpose(0, 1)
    # 計算每門課的平均分
    math_avg = scores_T[0].mean()
    english_avg = scores_T[1].mean()
    print("\n案例 2：數據處理中的轉置")
    print("原始成績（行=學生，列=科目）:\n", scores)
    print("轉置後（行=科目，列=學生）:\n", scores_T)
    print(f"數學平均分: {math_avg:.2f}")
    print(f"英語平均分: {english_avg:.2f}")

# 案例 3：線性回歸中的轉置
def example3_linear_regression():
    # 模擬數據：X 為特徵矩陣，y 為觀測值
    X = torch.tensor([[1, 2],
                      [1, 3],
                      [1, 4]], dtype=torch.float)
    y = torch.tensor([5, 7, 9], dtype=torch.float)
    # 計算 X^T
    X_T = X.transpose(0, 1)
    # 計算法方程 (X^T X)^(-1) X^T y
    XTX = torch.matmul(X_T, X)
    XTX_inv = torch.inverse(XTX)
    XTy = torch.matmul(X_T, y)
    weights = torch.matmul(XTX_inv, XTy)
    print("\n案例 3：線性回歸中的轉置")
    print("特徵矩陣 X:\n", X)
    print("觀測值 y:\n", y)
    print("X 的轉置 X^T:\n", X_T)
    print("線性回歸參數 (weights):\n", weights)


example1_basic_transpose()
example2_data_processing()
example3_linear_regression()

案例 1：基本矩陣轉置
原始張量 A:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
轉置後張量 A^T:
 tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

案例 2：數據處理中的轉置
原始成績（行=學生，列=科目）:
 tensor([[90., 85.],
        [88., 92.],
        [76., 80.]])
轉置後（行=科目，列=學生）:
 tensor([[90., 88., 76.],
        [85., 92., 80.]])
數學平均分: 84.67
英語平均分: 85.67

案例 3：線性回歸中的轉置
特徵矩陣 X:
 tensor([[1., 2.],
        [1., 3.],
        [1., 4.]])
觀測值 y:
 tensor([5., 7., 9.])
X 的轉置 X^T:
 tensor([[1., 1., 1.],
        [2., 3., 4.]])
線性回歸參數 (weights):
 tensor([1., 2.])


In [44]:
import time
import random
import sys # 用於判斷作業系統
import platform # 用於判斷作業系統
import os # 用於生成加密安全的隨機數

# UUID v1 的 Epoch (格里曆的開始日期)
# 1582年10月15日 00:00:00 UTC
# 到 1970年1月1日 00:00:00 UTC 之間的秒數差
# 這是預先計算好的常數，代表秒數的差異
# (1970-1582) * 365.2425天/年 * 24小時/天 * 60分/小時 * 60秒/分
# 加上閏年和其他月份的調整
UUID_TIME_EPOCH = 12219292800 * 10_000_000 # 轉換為 100 奈秒單位
# 12219292800 是從 1582-10-15 到 1970-01-01 的秒數
# 乘以 10_000_000 是因為 UUID 的時間單位是 100 奈秒

def _get_timestamp():
    """
    獲取 UUID 格式的時間戳 (100 奈秒為單位)。
    """
    # 獲取當前時間（UTC，單位為秒）
    current_time_ns = int(time.time() * 10_000_000) # 轉換為 100 奈秒單位
    # 加上 UUID 的時間偏移
    timestamp = current_time_ns + UUID_TIME_EPOCH
    return timestamp

_node_id = None # 用於緩存節點 ID，避免重複計算

def _get_node_id():
    """
    獲取節點 ID (MAC 地址或隨機生成的 48 位元數字)。
    標準 UUIDv1 節點 ID 是 48 位元。
    """
    global _node_id
    if _node_id is not None:
        return _node_id

    # 嘗試獲取 MAC 地址（這部分通常需要更複雜的處理或第三方庫）
    # 這裡我們只給出一個簡化且不保證成功的嘗試
    # 更好的方法是使用 `uuid.getnode()` 或 `psutil` 等庫

    # 由於我們自己實現，為了避免過於複雜，如果不能可靠地獲取，就用隨機數
    # 生成一個 48 位的隨機數作為節點 ID
    # 確保是偶數，因為標準中MAC地址的第一個位元組是0x01 (多播地址)
    # 我們這裡直接生成一個隨機數，並設置多播位為1
    _node_id = random.getrandbits(48) | 0x010000000000 # 設置多播位 (第8位元，使其看起來像 MAC 地址)

    # 你也可以嘗試使用以下方式來獲取 MAC 地址，但它們不總是可靠或跨平台：
    # try:
    #     import fcntl
    #     import socket
    #     s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    #     # 僅在 Linux/Unix 上有效
    #     info = fcntl.ioctl(s.fileno(), 0x8927,  # SIOCGIFHWADDR
    #                        struct.pack('256s', b'eth0'[:15]))
    #     _node_id = int.from_bytes(info[18:24], 'big')
    # except (IOError, AttributeError):
    #     # 如果失敗，則使用隨機數
    #     _node_id = random.getrandbits(48) | 0x010000000000
    
    return _node_id

_clock_seq = None # 用於緩存時鐘序列

def _get_clock_seq():
    """
    獲取時鐘序列 (14 位元隨機數)。
    """
    global _clock_seq
    if _clock_seq is None:
        # 初始時鐘序列，第一次生成時隨機化
        _clock_seq = random.getrandbits(14)
    # 在一個完整的實現中，需要有持久化機制來存儲時鐘序列並在時間回撥時更新它。
    # 這裡為了簡化，我們假設每次調用都可能是一個新的"會話"，所以可以簡單生成。
    # 如果要嚴格模擬，需要外部狀態管理。
    return _clock_seq

def generate_my_uuid_v1():
    """
    自己實現的 UUID 版本 1 生成器 (簡化版)。
    遵循 xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx 格式。
    """
    timestamp = _get_timestamp()
    clock_seq = _get_clock_seq()
    node_id = _get_node_id()

    # 提取時間戳的不同部分
    time_low = timestamp & 0xFFFFFFFF
    time_mid = (timestamp >> 32) & 0xFFFF
    time_high_and_version = ((timestamp >> 48) & 0x0FFF) | 0x1000 # 設置版本號為 1 (0001)

    # 處理時鐘序列和變體
    # UUID 變體設置為 10xx (RFC 4122)
    # 我們用 0x8000 確保前兩位是 10
    clock_seq_high_and_variant = ((clock_seq >> 8) & 0x3F) | 0x80 # 設置變體為 10
    clock_seq_low = clock_seq & 0xFF

    # 格式化為十六進位字串
    uuid_str = (f"{time_low:08x}-"
                f"{time_mid:04x}-"
                f"{time_high_and_version:04x}-"
                f"{clock_seq_high_and_variant:02x}{clock_seq_low:02x}-"
                f"{node_id:012x}")

    return uuid_str


print(generate_my_uuid_v1())

32d3cd9c-559d-11f0-af98-098899a15567


In [49]:
# 定義狀態旗標 (Flags)
IS_ALIVE = 1 << 0  # 00000001 (二進位)
IS_POISONED = 1 << 1 # 00000010
IS_PARALYZED = 1 << 2 # 00000100
IS_INVISIBLE = 1 << 3 # 00001000
IS_INVINCIBLE = 1 << 4 # 00010000
IS_CASTING = 1 << 5  # 00100000
IS_FLYING = 1 << 6   # 01000000
IS_IN_WATER = 1 << 7 # 10000000

# 假設角色初始狀態是活著
player_status = IS_ALIVE

print(f"初始狀態: {bin(player_status)}") # 輸出: 0b1

# 讓角色中毒
player_status = player_status | IS_POISONED # 使用 OR 運算來「設定」位元
print(f"中毒後狀態: {bin(player_status)}") # 輸出: 0b11 (00000011)

# 讓角色隱形
player_status = player_status | IS_INVISIBLE
print(f"隱形後狀態: {bin(player_status)}") # 輸出: 0b1011 (00001011)

# 檢查角色是否中毒
if (player_status & IS_POISONED): # 使用 AND 運算來「檢查」位元
    print("角色中毒了！")

# 檢查角色是否無敵
if not (player_status & IS_INVINCIBLE): # 如果結果是 0，表示無敵位元沒設定
    print("角色不是無敵的。")

# 解除中毒狀態
player_status = player_status & (~IS_POISONED) # 使用 AND 運算和 NOT 運算來「清除」位元
print(f"解除中毒後狀態: {bin(player_status)}") # 輸出: 0b1001 (00001001)

# 切換（翻轉）隱形狀態 (如果隱形就解除，如果沒隱形就隱形)
player_status = player_status ^ IS_INVISIBLE # 使用 XOR 運算來「翻轉」位元
print(f"翻轉隱形後狀態 (解除): {bin(player_status)}") # 輸出: 0b0001 (00000001)

player_status = player_status ^ IS_INVISIBLE
print(f"再次翻轉隱形後狀態 (隱形): {bin(player_status)}") # 輸出: 0b1001 (00001001)

初始狀態: 0b1
中毒後狀態: 0b11
隱形後狀態: 0b1011
角色中毒了！
角色不是無敵的。
解除中毒後狀態: 0b1001
翻轉隱形後狀態 (解除): 0b1
再次翻轉隱形後狀態 (隱形): 0b1001


In [57]:
num1 = 7
num2 = 2

# 判斷奇偶性 (一個數如果最右邊的位元是 1，就是奇數；是 0，就是偶數)
if (num1 & 1):
    print(f"{num1} 是奇數。")
else:
    print(f"{num1} 是偶數。")

if (num2 & 1):
    print(f"{num2} 是奇數。")
else:
    print(f"{num2} 是偶數。")

7 是奇數。
2 是偶數。


In [58]:
decimal_number = 123
binary_string = bin(decimal_number)
print(binary_string) # 輸出: 0b1111011

# 如果你不想看到 '0b' 前綴
print(binary_string[2:]) # 輸出: 1111011

0b1111011
1111011


In [68]:
import math
import mmh3 # 它提供 MurmurHash3，適合布隆過濾器

class BloomFilter:
    def __init__(self, capacity, false_positive_probability):
        """
        初始化布隆過濾器。

        Args:
            capacity (int): 預計要儲存的最大元素數量 (n)。
            false_positive_probability (float): 可接受的誤判率 (fp)。
        """
        if not (0 < false_positive_probability < 1):
            raise ValueError("誤判率必須介於 0 和 1 之間 (不包含 0 和 1)。")
        if not capacity > 0:
            raise ValueError("容量必須大於 0。")

        self.capacity = capacity
        self.false_positive_probability = false_positive_probability

        # 計算位元陣列的大小 (m)
        # m = -(n * ln(fp)) / (ln(2)^2)
        self.size = self._calculate_size(capacity, false_positive_probability)

        # 計算雜湊函數的數量 (k)
        # k = (m/n) * ln(2)
        self.hash_count = self._calculate_hash_count(self.size, capacity)

        # 初始化位元陣列，全部設為 False (0)
        self.bit_array = [False] * self.size

        # 用於追蹤實際已加入的元素數量（非必要，僅供參考）
        self.num_elements = 0

    def _calculate_size(self, n, fp):
        """根據預計元素數量和誤判率計算位元陣列的大小 (m)。"""
        m = -(n * math.log(fp)) / (math.log(2) ** 2)
        return int(m)

    def _calculate_hash_count(self, m, n):
        """根據位元陣列大小和預計元素數量計算最佳雜湊函數數量 (k)。"""
        k = (m / n) * math.log(2)
        return int(k)

    def _get_hashes(self, item):
        """
        產生多個雜湊值。
        這裡使用 MurmurHash3，並結合不同的 seed 來模擬多個雜湊函數。
        """
        hashes = []
        for i in range(self.hash_count):
            # mmh3.hash 會返回一個 32 位元的有符號整數
            # 確保索引為正數並在陣列範圍內
            h = mmh3.hash(item, i) % self.size
            hashes.append(h)
        return hashes

    def add(self, item):
        """將元素添加到布隆過濾器中。"""
        if self.num_elements >= self.capacity:
            print(f"警告：布隆過濾器已超出預設容量 {self.capacity}，誤判率可能增加。")

        hashes = self._get_hashes(item)
        for h in hashes:
            self.bit_array[h] = True
        self.num_elements += 1

    def contains(self, item):
        """檢查元素是否可能存在於布隆過濾器中。"""
        hashes = self._get_hashes(item)
        for h in hashes:
            if not self.bit_array[h]:
                return False  # 只要有一個位元為 False，則元素絕對不存在
        return True  # 所有位元都為 True，則元素可能存在

    def __len__(self):
        """返回已加入的元素數量。"""
        return self.num_elements

    def __contains__(self, item):
        """讓 'in' 操作符可以作用於布隆過濾器物件。"""
        return self.contains(item)

# 預計儲存 1000 個元素，可接受的誤判率為 0.1% (千分之一)
expected_items = 1000
fp_rate = 0.001

bloom = BloomFilter(expected_items, fp_rate)
print(f"初始化布隆過濾器：")
print(f"  預計容量 (n): {bloom.capacity}")
print(f"  目標誤判率 (fp): {bloom.false_positive_probability}")
print(f"  位元陣列大小 (m): {bloom.size} 位元 ({bloom.size / 8 / 1024:.2f} KB)")
print(f"  雜湊函數數量 (k): {bloom.hash_count}")
print("-" * 30)

# 1. 加入一些元素
words_to_add = ["aapl", "tsla", "net", "coin", "crwd"]
print(f"正在加入 {len(words_to_add)} 個元素...")
for word in words_to_add:
	bloom.add(word)
	print(f"  已加入: '{word}'")
print(f"目前已加入元素數量: {len(bloom)}")
print("-" * 30)

# 2. 查詢已存在的元素
print("查詢已存在的元素:")
print(f"'aapl' 存在嗎? {bloom.contains('aapl')}") # 應該是 True
print(f"'tsla' 存在嗎? {bloom.contains('tsla')}") # 應該是 True
print(f"'crwd' 存在嗎? {bloom.contains('crwd')}") # 應該是 True
print("-" * 30)

# 3. 查詢不存在的元素（可能會出現誤判）
print("查詢不存在的元素 (可能出現誤判):")
print(f"'msft' 存在嗎? {bloom.contains('msft')}") # 應該是 False，但有小機率是 True (誤判)
print(f"'meta' 存在嗎? {bloom.contains('meta')}")    # 應該是 False，但有小機率是 True (誤判)
print("-" * 30)

# 4. 測試大量數據下的誤判率（非精確測試，僅為概念演示）
print("測試大量數據下的誤判率（僅為概念演示，實際測試需更多數據點）:")
num_test_items = 5000  # 測試的項目數量，遠超過容量
false_positives = 0
for i in range(expected_items, expected_items + num_test_items):
	test_item = f"test_item_{i}"
	if bloom.contains(test_item):
		false_positives += 1

print(f"在 {num_test_items} 個未加入的項目中，有 {false_positives} 個誤判。")
if num_test_items > 0:
	actual_fp_rate = false_positives / num_test_items
	print(f"實際誤判率約為: {actual_fp_rate:.4f} (目標誤判率: {fp_rate:.4f})")
	print("請注意，對於小樣本，實際誤判率可能與目標誤判率有較大偏差。")

初始化布隆過濾器：
  預計容量 (n): 1000
  目標誤判率 (fp): 0.001
  位元陣列大小 (m): 14377 位元 (1.76 KB)
  雜湊函數數量 (k): 9
------------------------------
正在加入 5 個元素...
  已加入: 'aapl'
  已加入: 'tsla'
  已加入: 'net'
  已加入: 'coin'
  已加入: 'crwd'
目前已加入元素數量: 5
------------------------------
查詢已存在的元素:
'aapl' 存在嗎? True
'tsla' 存在嗎? True
'crwd' 存在嗎? True
------------------------------
查詢不存在的元素 (可能出現誤判):
'msft' 存在嗎? False
'meta' 存在嗎? False
------------------------------
測試大量數據下的誤判率（僅為概念演示，實際測試需更多數據點）:
在 5000 個未加入的項目中，有 0 個誤判。
實際誤判率約為: 0.0000 (目標誤判率: 0.0010)
請注意，對於小樣本，實際誤判率可能與目標誤判率有較大偏差。
